## OpenJDK 17 kullanarak temel image oluştur
#FROM openjdk:17-jdk-slim
#
## Uygulama jar dosyasını konteynere kopyala
#ARG JAR_FILE=target/user-service-0.0.1-SNAPSHOT.jar
#COPY ${JAR_FILE} app.jar
#
## Uygulamayı çalıştır
#ENTRYPOINT ["java", "-jar", "/app.jar"]
